version: '2.4'
services:
  backend-service:
    build:
      context: backend-service
    environment:
      - NODE_ENV=development
    command: npm run watch
    volumes:
      - ./backend-service:/code
    ports:
      - '3000:3000'

  frontend-service:
    build:
      context: frontend-service
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
    command: npm run start
    volumes:
      - ./frontend-service:/code
    ports:
      - '3010:3000'
